language: c
os:
 - linux
# - osx
install:
 - INSTALL_HERE="$(pwd)/libs"
 - LIBS_I="$INSTALL_HERE""/includes"
 - LIBS_L="$INSTALL_HERE""/objects"
 - . .travis/install_cmocka.sh
 - ls -R $INSTALL_HERE
 - . .travis/install_42FileChecker.sh
script:
 - make
 - make unit-tests
 - make clean-ft_printf
 - ls -R1 ./ft_printf
 - export CPATH="$(pwd)/ft_printf/libft"
 - bash ~/42FileChecker/42FileChecker.sh --project "ft_printf" --path "$(pwd)/ft_printf" --no-norminette
 - cat ~/42FileChecker/.my*
