ifndef ROOT
 ROOT := ..
 include $(ROOT)/Makefile
endif

TEST_SRCS := $(wildcard $(UTEST_DIR)/*.test.c)
TEST_OBJS := $(TEST_SRCS:.c=.o)
#BUILD_STAMPS := $(TEST_OBJS:.o=.build.stamp)
EXECUTION_STAMPS := $(TEST_OBJS:.o=.execution.stamp)

CFLAGS_UTEST = -fno-builtin -g
CFLAGS_UTEST += $(CFLAGS_MORE) #$(CFLAGS) were annoying the hell out of me




############
#BUILD TESTS

.PHONY : build_tests
build_tests : set_utest_flags def cmocka $(TEST_OBJS)

.PHONY : set_utest_flags
set_utest_flags :
	$(eval CFLAGS += $(CFLAGS_UTEST))

.PHONY : cmocka
cmocka : 
	@if $(CC) $(CFLAGS_UTEST)\
		-I $(LIBS_I) -L $(LIBS_L)\
	 	$(UTEST_DIR)/cmocka/check_install.c\
		 -lcmocka -o test.o\
		-Wl,-rpath=$$(readlink -e $(LIBS_L))\
		&& ./test.o .;\
	then\
		echo "cmocka already installed";\
	else\
		echo "installing cmocka";\
		$(MAKE) -C $(UTEST_DIR)/cmocka/;\
		mv $(UTEST_DIR)/cmocka/libcmocka* $(LIBS_L)/;\
		mv $(UTEST_DIR)/cmocka/cmocka.h $(LIBS_I)/;\
		echo "cmocka installed";\
	fi
	-@rm ./test.o

%.test.o $(UTEST_DIR)/%.test.o : $(UTEST_DIR)/%.test.c $(SRC_DIR)/%.c
	echo "$(LIBS_I)"
	$(CC) $(CFLAGS_UTEST)\
		-I $(LIBS_I) -I $(SRC_DIR)\
		-D main=testee_main\
		-D $(ARCH)\
		-include $(SRC_DIR)/$*.c\
		$<\
		-L $(LIBS_L)\
		-lcmocka -lft\
		-lm\
		-o $@\
		-Wl,-rpath=$$(readlink -e $(LIBS_L))

%.test.o : %.test.c $(UTEST_DIR)/printf_diff.c $(LIBS_L)/libftprintf.a
	$(CC) $(CFLAGS_UTEST)\
		-I $(SRC_DIR)\
		-I $(LIBS_I)\
		-D $(ARCH)\
		$<\
		-L $(LIBS_L)\
		-lftprintf\
		-lcmocka -lft\
		-lm\
		-o $@\
		-Wl,-rpath=$$(readlink -e $(LIBS_L))

%.test.c : $(UTEST_DIR)/cmocka/my_macro_overlay.h
	@:





############
#RUN TESTS :

.PHONY : unit-tests ut
unit-tests ut : list_tests build_tests run_tests

.PHONY : run_tests
run_tests : $(EXECUTION_STAMPS)

%.execution.stamp : %.o
	-./$*.o "$(UTEST_DIR)" \
	&& touch $@
#argument used to be
#	"$$(readlink -e $(UTEST_DIR))" \



###############
#MISCELLANEOUS:

.PHONY : all_unit_tests aut
all_unit_tests aut : clean-tests ut



.PHONY : clean-tests
clean-tests :
	-rm $(UTEST_DIR)/*.o
	-rm $(UTEST_DIR)/*.stamp



.PHONY : list_tests
list_tests :
	@echo "source dir is : $(SRC_DIR)"
	@echo "list of test sources:"
	@echo $(TEST_SRCS)
	@echo "list of test objects:"
	@echo $(TEST_OBJS)
